In [2]:
def function(x):
    return x**2 + 2*x - 3

file_obj = open("data/function.txt", "w")

for i in range(10000):
    file_obj.write(str(i) + " " + str(function(i)) + '\n')

file_obj.close()

In [9]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from src import ffnn_func as ffnn

name_file = './data/function.txt'
columns = ['x', 'y']

data_in = pd.read_csv(name_file,
                          names=columns,
                          sep=' ')

# separe the data in two groups train and test not random
train = data_in.sample(frac=1).reset_index(drop=True)
train = data_in[:int(len(train)*0.8)]
test = data_in[int(len(train)*0.8):]

X = train[['x']].to_numpy()
X_test = test[['x']].to_numpy()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
v, w = ffnn.ffnn(X, 4, train['y'], 10000, False, False)

In [16]:
print(v)
print(w)

[[4.21878427e-01 1.42785069e-01 3.92353401e+01 6.50711023e-01]
 [1.84100042e+01 6.58937727e-01 1.00847820e+04 5.79356693e-01]]
[[10429449.48991045]
 [10429449.61724051]
 [10429449.36755984]
 [10429399.31002948]
 [10429450.1158364 ]]


In [18]:
array = np.array([1,2,3])
G = ffnn.resolveForwardPropagation(array, v, w)
print(G)

Xb
[[1. 1.]
 [1. 2.]
 [1. 3.]]
F
[[0.99999999 0.69034288 1.         0.77383043]
 [1.         0.81163368 1.         0.85929229]
 [1.         0.89279348 1.         0.9159678 ]]
Fb
[[1.         0.99999999 0.69034288 1.         0.77383043]
 [1.         1.         0.81163368 1.         0.85929229]
 [1.         1.         0.89279348 1.         0.9159678 ]]
w
[[10429449.48991045]
 [10429449.61724051]
 [10429449.36755984]
 [10429399.31002948]
 [10429450.1158364 ]]
Fbb
[[46558820.31984126]
 [48715136.89966629]
 [50152683.27785868]]
[[1.]
 [1.]
 [1.]]
