In [31]:
%reload_ext autoreload

import numpy as np
import pandas as pd
import random
from matplotlib import pyplot as plt
import time
from src import ffnn

data = pd.read_csv('data/train.csv')

In [32]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [40]:
model = ffnn.FFNN(m)
model.train(X_train, Y_train, 0.1, 1000)

Iteration:  0
[1 7 3 ... 1 1 1] [8 1 2 ... 6 8 3]
0.09263414634146341
Iteration:  10
[3 0 3 ... 1 1 1] [8 1 2 ... 6 8 3]
0.1653658536585366
Iteration:  20
[3 7 3 ... 1 1 1] [8 1 2 ... 6 8 3]
0.2387560975609756
Iteration:  30
[3 7 3 ... 1 1 1] [8 1 2 ... 6 8 3]
0.29953658536585365
Iteration:  40
[3 7 3 ... 1 1 1] [8 1 2 ... 6 8 3]
0.34980487804878047
Iteration:  50
[3 7 3 ... 1 1 1] [8 1 2 ... 6 8 3]
0.39139024390243904
Iteration:  60
[3 7 3 ... 1 1 3] [8 1 2 ... 6 8 3]
0.43421951219512195
Iteration:  70
[3 7 2 ... 1 1 0] [8 1 2 ... 6 8 3]
0.4860243902439024
Iteration:  80
[8 7 2 ... 1 1 3] [8 1 2 ... 6 8 3]
0.532
Iteration:  90
[8 1 2 ... 1 1 3] [8 1 2 ... 6 8 3]
0.5715121951219512
Iteration:  100
[8 1 2 ... 3 1 3] [8 1 2 ... 6 8 3]
0.6047073170731707
Iteration:  110
[8 1 2 ... 3 1 3] [8 1 2 ... 6 8 3]
0.6317073170731707
Iteration:  120
[8 1 2 ... 2 8 3] [8 1 2 ... 6 8 3]
0.6539756097560976
Iteration:  130
[8 1 2 ... 2 8 3] [8 1 2 ... 6 8 3]
0.6714390243902439
Iteration:  140
[8 1 2 ..

(array([[-0.08400204, -0.49255843, -0.25163084, ...,  0.42435783,
          0.43512055,  0.45412144],
        [-0.26086836,  0.40524591,  0.27832289, ..., -0.27804687,
         -0.12923541,  0.05756846],
        [-0.27259234,  0.07366625,  0.46689634, ...,  0.01431183,
          0.03542342, -0.37261907],
        ...,
        [-0.39425975,  0.2902211 , -0.02452374, ..., -0.38466265,
         -0.25036247, -0.17233111],
        [ 0.46606401,  0.15769979, -0.00981264, ...,  0.2671928 ,
          0.06034052,  0.03811339],
        [-0.21982805,  0.17329112, -0.04873623, ...,  0.2473937 ,
         -0.33705998, -0.42412977]]),
 array([[0.98029527],
        [0.6213372 ],
        [0.34626195],
        [0.96975868],
        [0.35858777],
        [1.04114764],
        [0.95226307],
        [0.43427139],
        [0.59080099],
        [0.5157593 ]]),
 array([[-0.73900482,  0.47906268,  0.09679375,  0.12863698, -0.08767703,
          0.15675739, -0.38676458, -0.55751197, -0.22072508,  0.38484504],
  